color0 #11131c
color1 #ffb4ab
color2 #5dd5fc
color3 #88d1ec
color4 #b5c4ff
color5 #5dd5fc
color6 #88d1ec
color7 #e1e1ef
color8 #8b90a5
color9 #ffb4ab
color10 #5dd5fc
color11 #88d1ec
color12 #b5c4ff
color13 #5dd5fc
color14 #88d1ec
color15 #e1e1ef

cursor                #e1e1ef
cursor_text_color     #11131c
background            #11131c
foreground            #e1e1ef
selection_foreground  #c1c5dd
selection_background  #414659
active_border_color   #5dd5fc
inactive_border_color #414659
url_color             #5dd5fc

active_tab_foreground   #003543
active_tab_background   #5dd5fc
inactive_tab_foreground #c1c5dd
inactive_tab_background #414659
cursor_trail_color      #c1c5dd
