exec-once = noctalia
exec-once = hyprdynamicmonitors
exec-once = hypridle
exec-once = easyeffects --gapplication-service
exec-once = soteria

source = ~/.config/hypr/env.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/noctalia.conf
