[bar]
order = [ "default" ]

    [bar.default]
    capsule = true
    capsule_groups = [ "brightness+vol", "buttons_left", "buttons_right", "buttons_mid" ]
    capsule_radius = 5.0
    center = [ "clock", "media" ]
    end = [ "tray", "network", "bluetooth", "volume", "brightness", "battery", "clipboard", "control-center", "session" ]
    margin_edge = 5
    margin_ends = 30
    position = "left"
    radius = 7
    start = [ "launcher", "notifications", "workspaces" ]
    widget_spacing = 3

[desktop_widgets]
schema_version = 1
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002", "desktop-widget-0000000000000003" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    cx = 1396.0
    cy = 300.29998779296875
    output = "eDP-1"
    rotation = 0.0
    scale = 0.77398782968521118
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        aspect_ratio = 2.5
        bands = 32

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    cx = 1396.265380859375
    cy = 404.70001220703125
    output = "eDP-1"
    rotation = 0.0
    scale = 1.0
    type = "weather"

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    cx = 1284.25
    cy = 146.94758605957031
    output = "eDP-1"
    rotation = 0.0
    scale = 1.6754032373428345
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        aspect_ratio = 2.5
        bands = 32

[dock]
active_monitor_only = true
auto_hide = true
enabled = true
pinned = [ "zen-beta", "dolphin", "kitty" ]

[shell]
corner_radius_scale = 0.5
password_style = "random"
polkit_agent = true
settings_show_advanced = true
ui_scale = 0.94999998807907104

    [shell.animation]
    speed = 1.5500000715255737

    [shell.screen_corners]
    enabled = true
    size = 30

[theme]
source = "wallpaper"
wallpaper_scheme = "m3-fruit-salad"

    [theme.templates]
    builtin_ids = [ "hyprland", "gtk4", "gtk3", "kitty", "qt", "kcolorscheme" ]
    community_ids = [ "spicetify", "pywalfox", "vscode" ]

[wallpaper]
directory = "/home/yippie/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/yippie/Pictures/Wallpapers/tendou.png"

    [wallpaper.last]
    path = "/home/yippie/Pictures/Wallpapers/tendou.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/yippie/Pictures/Wallpapers/tendou.png"

[weather]
auto_locate = true

[widget.battery]
capsule = true

[widget.brightness]
capsule = true
capsule_group = "brightness+vol"
show_label = false

[widget.clipboard]
capsule = true
capsule_group = "buttons_right"

[widget.clock]
capsule = true
capsule_group = "buttons_mid"

[widget.control-center]
capsule = true
capsule_group = "buttons_right"

[widget.launcher]
capsule = true
capsule_group = "buttons_left"
glyph = "rocket"

[widget.media]
capsule = true
capsule_group = "buttons_mid"

[widget.network]
capsule = true
show_label = false

[widget.notifications]
capsule = true
capsule_group = "buttons_left"

[widget.session]
capsule = true
capsule_group = "buttons_right"

[widget.tray]
capsule = true

[widget.volume]
capsule = true
capsule_group = "brightness+vol"
show_label = false

[widget.workspaces]
capsule = true
capsule_group = "buttons_left"
display = "id"
